USE CopaDoMundo;

-- Comandos para limpar as tabelas antes de inserir (descomente se necessário)
/*
DELETE FROM ParticipacaoJogador;
DELETE FROM Jogador;
DELETE FROM EdicaoSede;
DELETE FROM Partida;
DELETE FROM Edicao;
DELETE FROM Pais;
*/

-- Inserção de Países
INSERT IGNORE INTO Pais (nome) VALUES ('Alemanha');
INSERT IGNORE INTO Pais (nome) VALUES ('Argentina');
INSERT IGNORE INTO Pais (nome) VALUES ('Austrália');
INSERT IGNORE INTO Pais (nome) VALUES ('Brasil');
INSERT IGNORE INTO Pais (nome) VALUES ('Bulgária');
INSERT IGNORE INTO Pais (nome) VALUES ('Bélgica');
INSERT IGNORE INTO Pais (nome) VALUES ('Camarões');
INSERT IGNORE INTO Pais (nome) VALUES ('Catar');
INSERT IGNORE INTO Pais (nome) VALUES ('Chile');
INSERT IGNORE INTO Pais (nome) VALUES ('Colômbia');
INSERT IGNORE INTO Pais (nome) VALUES ('Coreia do Sul');
INSERT IGNORE INTO Pais (nome) VALUES ('Croácia');
INSERT IGNORE INTO Pais (nome) VALUES ('Dinamarca');
INSERT IGNORE INTO Pais (nome) VALUES ('Equador');
INSERT IGNORE INTO Pais (nome) VALUES ('Espanha');
INSERT IGNORE INTO Pais (nome) VALUES ('Estados Unidos');
INSERT IGNORE INTO Pais (nome) VALUES ('França');
INSERT IGNORE INTO Pais (nome) VALUES ('Gana');
INSERT IGNORE INTO Pais (nome) VALUES ('Hungria');
INSERT IGNORE INTO Pais (nome) VALUES ('Inglaterra');
INSERT IGNORE INTO Pais (nome) VALUES ('Irlanda do Norte');
INSERT IGNORE INTO Pais (nome) VALUES ('Itália');
INSERT IGNORE INTO Pais (nome) VALUES ('Iugoslávia');
INSERT IGNORE INTO Pais (nome) VALUES ('Japão');
INSERT IGNORE INTO Pais (nome) VALUES ('Marrocos');
INSERT IGNORE INTO Pais (nome) VALUES ('México');
INSERT IGNORE INTO Pais (nome) VALUES ('Países Baixos');
INSERT IGNORE INTO Pais (nome) VALUES ('Peru');
INSERT IGNORE INTO Pais (nome) VALUES ('Polônia');
INSERT IGNORE INTO Pais (nome) VALUES ('Portugal');
INSERT IGNORE INTO Pais (nome) VALUES ('Rússia');
INSERT IGNORE INTO Pais (nome) VALUES ('Suécia');
INSERT IGNORE INTO Pais (nome) VALUES ('Suíça');
INSERT IGNORE INTO Pais (nome) VALUES ('Tchecoslováquia');
INSERT IGNORE INTO Pais (nome) VALUES ('Turquia');
INSERT IGNORE INTO Pais (nome) VALUES ('Uruguai');
INSERT IGNORE INTO Pais (nome) VALUES ('África do Sul');
INSERT IGNORE INTO Pais (nome) VALUES ('Áustria');

-- Inserção de Edições
INSERT IGNORE INTO Edicao (ano) VALUES (1930);
INSERT IGNORE INTO Edicao (ano) VALUES (1934);
INSERT IGNORE INTO Edicao (ano) VALUES (1938);
INSERT IGNORE INTO Edicao (ano) VALUES (1950);
INSERT IGNORE INTO Edicao (ano) VALUES (1954);
INSERT IGNORE INTO Edicao (ano) VALUES (1958);
INSERT IGNORE INTO Edicao (ano) VALUES (1962);
INSERT IGNORE INTO Edicao (ano) VALUES (1966);
INSERT IGNORE INTO Edicao (ano) VALUES (1970);
INSERT IGNORE INTO Edicao (ano) VALUES (1974);
INSERT IGNORE INTO Edicao (ano) VALUES (1978);
INSERT IGNORE INTO Edicao (ano) VALUES (1982);
INSERT IGNORE INTO Edicao (ano) VALUES (1986);
INSERT IGNORE INTO Edicao (ano) VALUES (1990);
INSERT IGNORE INTO Edicao (ano) VALUES (1994);
INSERT IGNORE INTO Edicao (ano) VALUES (1998);
INSERT IGNORE INTO Edicao (ano) VALUES (2002);
INSERT IGNORE INTO Edicao (ano) VALUES (2006);
INSERT IGNORE INTO Edicao (ano) VALUES (2010);
INSERT IGNORE INTO Edicao (ano) VALUES (2014);
INSERT IGNORE INTO Edicao (ano) VALUES (2018);
INSERT IGNORE INTO Edicao (ano) VALUES (2022);

-- Vinculação de Sedes
INSERT IGNORE INTO EdicaoSede (idEdicao, idPais) VALUES (1, 36);
INSERT IGNORE INTO EdicaoSede (idEdicao, idPais) VALUES (2, 22);
INSERT IGNORE INTO EdicaoSede (idEdicao, idPais) VALUES (3, 17);
INSERT IGNORE INTO EdicaoSede (idEdicao, idPais) VALUES (4, 4);
INSERT IGNORE INTO EdicaoSede (idEdicao, idPais) VALUES (5, 33);
INSERT IGNORE INTO EdicaoSede (idEdicao, idPais) VALUES (6, 32);
INSERT IGNORE INTO EdicaoSede (idEdicao, idPais) VALUES (7, 9);
INSERT IGNORE INTO EdicaoSede (idEdicao, idPais) VALUES (8, 20);
INSERT IGNORE INTO EdicaoSede (idEdicao, idPais) VALUES (9, 26);
INSERT IGNORE INTO EdicaoSede (idEdicao, idPais) VALUES (10, 1);
INSERT IGNORE INTO EdicaoSede (idEdicao, idPais) VALUES (11, 2);
INSERT IGNORE INTO EdicaoSede (idEdicao, idPais) VALUES (12, 15);
INSERT IGNORE INTO EdicaoSede (idEdicao, idPais) VALUES (13, 26);
INSERT IGNORE INTO EdicaoSede (idEdicao, idPais) VALUES (14, 22);
INSERT IGNORE INTO EdicaoSede (idEdicao, idPais) VALUES (15, 16);
INSERT IGNORE INTO EdicaoSede (idEdicao, idPais) VALUES (16, 17);
INSERT IGNORE INTO EdicaoSede (idEdicao, idPais) VALUES (17, 11);
INSERT IGNORE INTO EdicaoSede (idEdicao, idPais) VALUES (17, 24);
INSERT IGNORE INTO EdicaoSede (idEdicao, idPais) VALUES (18, 1);
INSERT IGNORE INTO EdicaoSede (idEdicao, idPais) VALUES (19, 37);
INSERT IGNORE INTO EdicaoSede (idEdicao, idPais) VALUES (20, 4);
INSERT IGNORE INTO EdicaoSede (idEdicao, idPais) VALUES (21, 31);
INSERT IGNORE INTO EdicaoSede (idEdicao, idPais) VALUES (22, 8);

-- Inserção de Partidas
INSERT IGNORE INTO Partida (idEdicao, fase, idGanhador, idPerdedor, golsGanhador, golsPerdedor, observacoesPlacar) VALUES (1, 'Final', 36, 2, 4, 2, NULL);
INSERT IGNORE INTO Partida (idEdicao, fase, idGanhador, idPerdedor, golsGanhador, golsPerdedor, observacoesPlacar) VALUES (1, 'Disputa 3º Lugar', 16, 23, NULL, NULL, NULL);
INSERT IGNORE INTO Partida (idEdicao, fase, idGanhador, idPerdedor, golsGanhador, golsPerdedor, observacoesPlacar) VALUES (2, 'Final', 22, 34, 2, 1, '(pro)');
INSERT IGNORE INTO Partida (idEdicao, fase, idGanhador, idPerdedor, golsGanhador, golsPerdedor, observacoesPlacar) VALUES (2, 'Disputa 3º Lugar', 1, 38, 3, 2, NULL);
INSERT IGNORE INTO Partida (idEdicao, fase, idGanhador, idPerdedor, golsGanhador, golsPerdedor, observacoesPlacar) VALUES (3, 'Final', 22, 19, 4, 2, NULL);
INSERT IGNORE INTO Partida (idEdicao, fase, idGanhador, idPerdedor, golsGanhador, golsPerdedor, observacoesPlacar) VALUES (3, 'Disputa 3º Lugar', 4, 32, 4, 2, NULL);
INSERT IGNORE INTO Partida (idEdicao, fase, idGanhador, idPerdedor, golsGanhador, golsPerdedor, observacoesPlacar) VALUES (4, 'Final', 36, 4, 2, 1, '[nota 2]');
INSERT IGNORE INTO Partida (idEdicao, fase, idGanhador, idPerdedor, golsGanhador, golsPerdedor, observacoesPlacar) VALUES (4, 'Disputa 3º Lugar', 32, 15, 3, 1, '[nota 2]');
INSERT IGNORE INTO Partida (idEdicao, fase, idGanhador, idPerdedor, golsGanhador, golsPerdedor, observacoesPlacar) VALUES (5, 'Final', 1, 19, 3, 2, NULL);
INSERT IGNORE INTO Partida (idEdicao, fase, idGanhador, idPerdedor, golsGanhador, golsPerdedor, observacoesPlacar) VALUES (5, 'Disputa 3º Lugar', 38, 36, 3, 1, NULL);
INSERT IGNORE INTO Partida (idEdicao, fase, idGanhador, idPerdedor, golsGanhador, golsPerdedor, observacoesPlacar) VALUES (6, 'Final', 4, 32, 5, 2, NULL);
INSERT IGNORE INTO Partida (idEdicao, fase, idGanhador, idPerdedor, golsGanhador, golsPerdedor, observacoesPlacar) VALUES (6, 'Disputa 3º Lugar', 17, 1, 6, 3, NULL);
INSERT IGNORE INTO Partida (idEdicao, fase, idGanhador, idPerdedor, golsGanhador, golsPerdedor, observacoesPlacar) VALUES (7, 'Final', 4, 34, 3, 1, NULL);
INSERT IGNORE INTO Partida (idEdicao, fase, idGanhador, idPerdedor, golsGanhador, golsPerdedor, observacoesPlacar) VALUES (7, 'Disputa 3º Lugar', 9, 23, 1, 0, NULL);
INSERT IGNORE INTO Partida (idEdicao, fase, idGanhador, idPerdedor, golsGanhador, golsPerdedor, observacoesPlacar) VALUES (8, 'Final', 20, 1, 4, 2, '(pro)');
INSERT IGNORE INTO Partida (idEdicao, fase, idGanhador, idPerdedor, golsGanhador, golsPerdedor, observacoesPlacar) VALUES (8, 'Disputa 3º Lugar', 30, 31, 2, 1, NULL);
INSERT IGNORE INTO Partida (idEdicao, fase, idGanhador, idPerdedor, golsGanhador, golsPerdedor, observacoesPlacar) VALUES (9, 'Final', 4, 22, 4, 1, NULL);
INSERT IGNORE INTO Partida (idEdicao, fase, idGanhador, idPerdedor, golsGanhador, golsPerdedor, observacoesPlacar) VALUES (9, 'Disputa 3º Lugar', 1, 36, 1, 0, NULL);
INSERT IGNORE INTO Partida (idEdicao, fase, idGanhador, idPerdedor, golsGanhador, golsPerdedor, observacoesPlacar) VALUES (10, 'Final', 1, 27, 2, 1, NULL);
INSERT IGNORE INTO Partida (idEdicao, fase, idGanhador, idPerdedor, golsGanhador, golsPerdedor, observacoesPlacar) VALUES (10, 'Disputa 3º Lugar', 29, 4, 1, 0, NULL);
INSERT IGNORE INTO Partida (idEdicao, fase, idGanhador, idPerdedor, golsGanhador, golsPerdedor, observacoesPlacar) VALUES (11, 'Final', 2, 27, 3, 1, '(pro)');
INSERT IGNORE INTO Partida (idEdicao, fase, idGanhador, idPerdedor, golsGanhador, golsPerdedor, observacoesPlacar) VALUES (11, 'Disputa 3º Lugar', 4, 22, 2, 1, NULL);
INSERT IGNORE INTO Partida (idEdicao, fase, idGanhador, idPerdedor, golsGanhador, golsPerdedor, observacoesPlacar) VALUES (12, 'Final', 22, 1, 3, 1, NULL);
INSERT IGNORE INTO Partida (idEdicao, fase, idGanhador, idPerdedor, golsGanhador, golsPerdedor, observacoesPlacar) VALUES (12, 'Disputa 3º Lugar', 29, 17, 3, 2, NULL);
INSERT IGNORE INTO Partida (idEdicao, fase, idGanhador, idPerdedor, golsGanhador, golsPerdedor, observacoesPlacar) VALUES (13, 'Final', 2, 1, 3, 2, NULL);
INSERT IGNORE INTO Partida (idEdicao, fase, idGanhador, idPerdedor, golsGanhador, golsPerdedor, observacoesPlacar) VALUES (13, 'Disputa 3º Lugar', 17, 6, 4, 2, '(pro)');
INSERT IGNORE INTO Partida (idEdicao, fase, idGanhador, idPerdedor, golsGanhador, golsPerdedor, observacoesPlacar) VALUES (14, 'Final', 1, 2, 1, 0, NULL);
INSERT IGNORE INTO Partida (idEdicao, fase, idGanhador, idPerdedor, golsGanhador, golsPerdedor, observacoesPlacar) VALUES (14, 'Disputa 3º Lugar', 22, 20, 2, 1, NULL);
INSERT IGNORE INTO Partida (idEdicao, fase, idGanhador, idPerdedor, golsGanhador, golsPerdedor, observacoesPlacar) VALUES (15, 'Final', 4, 22, 0, 0, '(pro) 3 – 2 (pen)');
INSERT IGNORE INTO Partida (idEdicao, fase, idGanhador, idPerdedor, golsGanhador, golsPerdedor, observacoesPlacar) VALUES (15, 'Disputa 3º Lugar', 32, 5, 4, 0, NULL);
INSERT IGNORE INTO Partida (idEdicao, fase, idGanhador, idPerdedor, golsGanhador, golsPerdedor, observacoesPlacar) VALUES (16, 'Final', 17, 4, 3, 0, NULL);
INSERT IGNORE INTO Partida (idEdicao, fase, idGanhador, idPerdedor, golsGanhador, golsPerdedor, observacoesPlacar) VALUES (16, 'Disputa 3º Lugar', 12, 27, 2, 1, NULL);
INSERT IGNORE INTO Partida (idEdicao, fase, idGanhador, idPerdedor, golsGanhador, golsPerdedor, observacoesPlacar) VALUES (17, 'Final', 4, 1, 2, 0, NULL);
INSERT IGNORE INTO Partida (idEdicao, fase, idGanhador, idPerdedor, golsGanhador, golsPerdedor, observacoesPlacar) VALUES (17, 'Disputa 3º Lugar', 35, 11, 3, 2, NULL);
INSERT IGNORE INTO Partida (idEdicao, fase, idGanhador, idPerdedor, golsGanhador, golsPerdedor, observacoesPlacar) VALUES (18, 'Final', 22, 17, 1, 1, '(pro) 5 – 3 (pen)');
INSERT IGNORE INTO Partida (idEdicao, fase, idGanhador, idPerdedor, golsGanhador, golsPerdedor, observacoesPlacar) VALUES (18, 'Disputa 3º Lugar', 1, 30, 3, 1, NULL);
INSERT IGNORE INTO Partida (idEdicao, fase, idGanhador, idPerdedor, golsGanhador, golsPerdedor, observacoesPlacar) VALUES (19, 'Final', 15, 27, 1, 0, '(pro)');
INSERT IGNORE INTO Partida (idEdicao, fase, idGanhador, idPerdedor, golsGanhador, golsPerdedor, observacoesPlacar) VALUES (19, 'Disputa 3º Lugar', 1, 36, 3, 2, NULL);
INSERT IGNORE INTO Partida (idEdicao, fase, idGanhador, idPerdedor, golsGanhador, golsPerdedor, observacoesPlacar) VALUES (20, 'Final', 1, 2, 1, 0, '(pro)');
INSERT IGNORE INTO Partida (idEdicao, fase, idGanhador, idPerdedor, golsGanhador, golsPerdedor, observacoesPlacar) VALUES (20, 'Disputa 3º Lugar', 27, 4, 3, 0, NULL);
INSERT IGNORE INTO Partida (idEdicao, fase, idGanhador, idPerdedor, golsGanhador, golsPerdedor, observacoesPlacar) VALUES (21, 'Final', 17, 12, 4, 2, NULL);
INSERT IGNORE INTO Partida (idEdicao, fase, idGanhador, idPerdedor, golsGanhador, golsPerdedor, observacoesPlacar) VALUES (21, 'Disputa 3º Lugar', 6, 20, 2, 0, NULL);
INSERT IGNORE INTO Partida (idEdicao, fase, idGanhador, idPerdedor, golsGanhador, golsPerdedor, observacoesPlacar) VALUES (22, 'Final', 2, 17, 3, 3, '(pro) 4 – 2 (pen)');
INSERT IGNORE INTO Partida (idEdicao, fase, idGanhador, idPerdedor, golsGanhador, golsPerdedor, observacoesPlacar) VALUES (22, 'Disputa 3º Lugar', 12, 25, 2, 1, NULL);

-- Inserção de Jogadores
INSERT IGNORE INTO Jogador (nome, idPais, totalGols, totalPartidas) VALUES ('Miroslav Klose', 1, 16, 24);
INSERT IGNORE INTO Jogador (nome, idPais, totalGols, totalPartidas) VALUES ('Ronaldo', 4, 15, 19);
INSERT IGNORE INTO Jogador (nome, idPais, totalGols, totalPartidas) VALUES ('Gerd Müller', 1, 14, 13);
INSERT IGNORE INTO Jogador (nome, idPais, totalGols, totalPartidas) VALUES ('Just Fontaine', 17, 13, 6);
INSERT IGNORE INTO Jogador (nome, idPais, totalGols, totalPartidas) VALUES ('Lionel Messi', 2, 13, 26);
INSERT IGNORE INTO Jogador (nome, idPais, totalGols, totalPartidas) VALUES ('Pelé', 4, 12, 14);
INSERT IGNORE INTO Jogador (nome, idPais, totalGols, totalPartidas) VALUES ('Kylian Mbappé', 17, 12, 14);
INSERT IGNORE INTO Jogador (nome, idPais, totalGols, totalPartidas) VALUES ('Sándor Kocsis', 19, 11, 5);
INSERT IGNORE INTO Jogador (nome, idPais, totalGols, totalPartidas) VALUES ('Jürgen Klinsmann', 1, 11, 17);
INSERT IGNORE INTO Jogador (nome, idPais, totalGols, totalPartidas) VALUES ('Helmut Rahn', 1, 10, 10);
INSERT IGNORE INTO Jogador (nome, idPais, totalGols, totalPartidas) VALUES ('Gary Lineker', 20, 10, 12);
INSERT IGNORE INTO Jogador (nome, idPais, totalGols, totalPartidas) VALUES ('Gabriel Batistuta', 2, 10, 12);
INSERT IGNORE INTO Jogador (nome, idPais, totalGols, totalPartidas) VALUES ('Teófilo Cubillas', 28, 10, 13);
INSERT IGNORE INTO Jogador (nome, idPais, totalGols, totalPartidas) VALUES ('Thomas Müller', 1, 10, 17);
INSERT IGNORE INTO Jogador (nome, idPais, totalGols, totalPartidas) VALUES ('Grzegorz Lato', 29, 10, 20);
INSERT IGNORE INTO Jogador (nome, idPais, totalGols, totalPartidas) VALUES ('Ademir de Menezes', 4, 9, 6);
INSERT IGNORE INTO Jogador (nome, idPais, totalGols, totalPartidas) VALUES ('Eusébio', 30, 9, 6);
INSERT IGNORE INTO Jogador (nome, idPais, totalGols, totalPartidas) VALUES ('Christian Vieri', 22, 9, 9);
INSERT IGNORE INTO Jogador (nome, idPais, totalGols, totalPartidas) VALUES ('Vavá', 4, 9, 10);
INSERT IGNORE INTO Jogador (nome, idPais, totalGols, totalPartidas) VALUES ('David Villa', 15, 9, 12);
INSERT IGNORE INTO Jogador (nome, idPais, totalGols, totalPartidas) VALUES ('Paolo Rossi', 22, 9, 14);
INSERT IGNORE INTO Jogador (nome, idPais, totalGols, totalPartidas) VALUES ('Jairzinho', 4, 9, 16);
INSERT IGNORE INTO Jogador (nome, idPais, totalGols, totalPartidas) VALUES ('Roberto Baggio', 22, 9, 16);
INSERT IGNORE INTO Jogador (nome, idPais, totalGols, totalPartidas) VALUES ('Karl-Heinz Rummenigge', 1, 9, 19);
INSERT IGNORE INTO Jogador (nome, idPais, totalGols, totalPartidas) VALUES ('Uwe Seeler', 1, 9, 21);
INSERT IGNORE INTO Jogador (nome, idPais, totalGols, totalPartidas) VALUES ('Guillermo Stábile', 2, 8, 4);
INSERT IGNORE INTO Jogador (nome, idPais, totalGols, totalPartidas) VALUES ('Leônidas da Silva', 4, 8, 5);
INSERT IGNORE INTO Jogador (nome, idPais, totalGols, totalPartidas) VALUES ('Óscar Míguez', 36, 8, 7);
INSERT IGNORE INTO Jogador (nome, idPais, totalGols, totalPartidas) VALUES ('Harry Kane', 20, 8, 11);
INSERT IGNORE INTO Jogador (nome, idPais, totalGols, totalPartidas) VALUES ('Neymar', 4, 8, 13);
INSERT IGNORE INTO Jogador (nome, idPais, totalGols, totalPartidas) VALUES ('Rivaldo', 4, 8, 14);
INSERT IGNORE INTO Jogador (nome, idPais, totalGols, totalPartidas) VALUES ('Rudi Völler', 1, 8, 15);
INSERT IGNORE INTO Jogador (nome, idPais, totalGols, totalPartidas) VALUES ('Diego Maradona', 2, 8, 21);
INSERT IGNORE INTO Jogador (nome, idPais, totalGols, totalPartidas) VALUES ('Cristiano Ronaldo', 30, 8, 22);
INSERT IGNORE INTO Jogador (nome, idPais, totalGols, totalPartidas) VALUES ('Oldřich Nejedlý', 34, 7, 6);
INSERT IGNORE INTO Jogador (nome, idPais, totalGols, totalPartidas) VALUES ('Lajos Tichy', 19, 7, 8);
INSERT IGNORE INTO Jogador (nome, idPais, totalGols, totalPartidas) VALUES ('Careca', 4, 7, 9);
INSERT IGNORE INTO Jogador (nome, idPais, totalGols, totalPartidas) VALUES ('Andrzej Szarmach', 29, 7, 13);
INSERT IGNORE INTO Jogador (nome, idPais, totalGols, totalPartidas) VALUES ('Johnny Rep', 27, 7, 13);
INSERT IGNORE INTO Jogador (nome, idPais, totalGols, totalPartidas) VALUES ('Luis Suárez', 36, 7, 15);
INSERT IGNORE INTO Jogador (nome, idPais, totalGols, totalPartidas) VALUES ('Hans Schäfer', 1, 7, 15);
INSERT IGNORE INTO Jogador (nome, idPais, totalGols, totalPartidas) VALUES ('Josef Hügi', 33, 6, 3);
INSERT IGNORE INTO Jogador (nome, idPais, totalGols, totalPartidas) VALUES ('Oleg Salenko', 31, 6, 3);
INSERT IGNORE INTO Jogador (nome, idPais, totalGols, totalPartidas) VALUES ('Max Morlock', 1, 6, 5);
INSERT IGNORE INTO Jogador (nome, idPais, totalGols, totalPartidas) VALUES ('Erich Probst', 38, 6, 5);
INSERT IGNORE INTO Jogador (nome, idPais, totalGols, totalPartidas) VALUES ('György Sárosi', 19, 6, 5);
INSERT IGNORE INTO Jogador (nome, idPais, totalGols, totalPartidas) VALUES ('Enner Valencia', 14, 6, 6);
INSERT IGNORE INTO Jogador (nome, idPais, totalGols, totalPartidas) VALUES ('Salvatore Schillaci', 22, 6, 7);
INSERT IGNORE INTO Jogador (nome, idPais, totalGols, totalPartidas) VALUES ('Davor Šuker', 12, 6, 8);
INSERT IGNORE INTO Jogador (nome, idPais, totalGols, totalPartidas) VALUES ('James Rodríguez', 10, 6, 8);
INSERT IGNORE INTO Jogador (nome, idPais, totalGols, totalPartidas) VALUES ('Helmut Haller', 1, 6, 9);
INSERT IGNORE INTO Jogador (nome, idPais, totalGols, totalPartidas) VALUES ('Hristo Stoichkov', 5, 6, 10);
INSERT IGNORE INTO Jogador (nome, idPais, totalGols, totalPartidas) VALUES ('Diego Forlán', 36, 6, 10);
INSERT IGNORE INTO Jogador (nome, idPais, totalGols, totalPartidas) VALUES ('Asamoah Gyan', 18, 6, 11);
INSERT IGNORE INTO Jogador (nome, idPais, totalGols, totalPartidas) VALUES ('Dennis Bergkamp', 27, 6, 12);
INSERT IGNORE INTO Jogador (nome, idPais, totalGols, totalPartidas) VALUES ('Rob Rensenbrink', 27, 6, 13);
INSERT IGNORE INTO Jogador (nome, idPais, totalGols, totalPartidas) VALUES ('Rivellino', 4, 6, 15);
INSERT IGNORE INTO Jogador (nome, idPais, totalGols, totalPartidas) VALUES ('Bebeto', 4, 6, 15);
INSERT IGNORE INTO Jogador (nome, idPais, totalGols, totalPartidas) VALUES ('Arjen Robben', 27, 6, 15);
INSERT IGNORE INTO Jogador (nome, idPais, totalGols, totalPartidas) VALUES ('Zbigniew Boniek', 29, 6, 16);
INSERT IGNORE INTO Jogador (nome, idPais, totalGols, totalPartidas) VALUES ('Ivan Perišić', 12, 6, 17);
INSERT IGNORE INTO Jogador (nome, idPais, totalGols, totalPartidas) VALUES ('Thierry Henry', 17, 6, 17);
INSERT IGNORE INTO Jogador (nome, idPais, totalGols, totalPartidas) VALUES ('Wesley Sneijder', 27, 6, 17);
INSERT IGNORE INTO Jogador (nome, idPais, totalGols, totalPartidas) VALUES ('Robin van Persie', 27, 6, 17);
INSERT IGNORE INTO Jogador (nome, idPais, totalGols, totalPartidas) VALUES ('Mario Kempes', 2, 6, 18);
INSERT IGNORE INTO Jogador (nome, idPais, totalGols, totalPartidas) VALUES ('Lothar Matthäus', 1, 6, 25);
INSERT IGNORE INTO Jogador (nome, idPais, totalGols, totalPartidas) VALUES ('Pedro Cea', 36, 5, 4);
INSERT IGNORE INTO Jogador (nome, idPais, totalGols, totalPartidas) VALUES ('Silvio Piola', 22, 5, 4);
INSERT IGNORE INTO Jogador (nome, idPais, totalGols, totalPartidas) VALUES ('Gyula Zsengellér', 19, 5, 4);
INSERT IGNORE INTO Jogador (nome, idPais, totalGols, totalPartidas) VALUES ('Peter McParland', 21, 5, 5);
INSERT IGNORE INTO Jogador (nome, idPais, totalGols, totalPartidas) VALUES ('Tomáš Skuhravý', 34, 5, 5);
INSERT IGNORE INTO Jogador (nome, idPais, totalGols, totalPartidas) VALUES ('Juan Alberto Schiaffino', 36, 5, 6);
INSERT IGNORE INTO Jogador (nome, idPais, totalGols, totalPartidas) VALUES ('Geoff Hurst', 20, 5, 6);
INSERT IGNORE INTO Jogador (nome, idPais, totalGols, totalPartidas) VALUES ('Jon Dahl Tomasson', 13, 5, 6);
INSERT IGNORE INTO Jogador (nome, idPais, totalGols, totalPartidas) VALUES ('Alessandro Altobelli', 22, 5, 7);
INSERT IGNORE INTO Jogador (nome, idPais, totalGols, totalPartidas) VALUES ('Kennet Andersson', 32, 5, 7);
INSERT IGNORE INTO Jogador (nome, idPais, totalGols, totalPartidas) VALUES ('Fernando Morientes', 15, 5, 7);
INSERT IGNORE INTO Jogador (nome, idPais, totalGols, totalPartidas) VALUES ('Romário', 4, 5, 8);
INSERT IGNORE INTO Jogador (nome, idPais, totalGols, totalPartidas) VALUES ('Mario Mandžukić', 12, 5, 8);
INSERT IGNORE INTO Jogador (nome, idPais, totalGols, totalPartidas) VALUES ('Marc Wilmots', 6, 5, 8);
INSERT IGNORE INTO Jogador (nome, idPais, totalGols, totalPartidas) VALUES ('Tim Cahill', 3, 5, 9);
INSERT IGNORE INTO Jogador (nome, idPais, totalGols, totalPartidas) VALUES ('Valentin Ivanov', 31, 5, 9);
INSERT IGNORE INTO Jogador (nome, idPais, totalGols, totalPartidas) VALUES ('Roger Milla', 7, 5, 9);
INSERT IGNORE INTO Jogador (nome, idPais, totalGols, totalPartidas) VALUES ('Emilio Butragueño', 15, 5, 9);
INSERT IGNORE INTO Jogador (nome, idPais, totalGols, totalPartidas) VALUES ('Hans Krankl', 38, 5, 10);
INSERT IGNORE INTO Jogador (nome, idPais, totalGols, totalPartidas) VALUES ('Raúl', 15, 5, 11);
INSERT IGNORE INTO Jogador (nome, idPais, totalGols, totalPartidas) VALUES ('Xherdan Shaqiri', 33, 5, 12);
INSERT IGNORE INTO Jogador (nome, idPais, totalGols, totalPartidas) VALUES ('Romelu Lukaku', 6, 5, 12);
INSERT IGNORE INTO Jogador (nome, idPais, totalGols, totalPartidas) VALUES ('Garrincha', 4, 5, 12);
INSERT IGNORE INTO Jogador (nome, idPais, totalGols, totalPartidas) VALUES ('Johan Neeskens', 27, 5, 12);
INSERT IGNORE INTO Jogador (nome, idPais, totalGols, totalPartidas) VALUES ('Fernando Hierro', 15, 5, 12);
INSERT IGNORE INTO Jogador (nome, idPais, totalGols, totalPartidas) VALUES ('Zinédine Zidane', 17, 5, 12);
INSERT IGNORE INTO Jogador (nome, idPais, totalGols, totalPartidas) VALUES ('Landon Donovan', 16, 5, 12);
INSERT IGNORE INTO Jogador (nome, idPais, totalGols, totalPartidas) VALUES ('Gonzalo Higuaín', 2, 5, 13);
INSERT IGNORE INTO Jogador (nome, idPais, totalGols, totalPartidas) VALUES ('Henrik Larsson', 32, 5, 13);
INSERT IGNORE INTO Jogador (nome, idPais, totalGols, totalPartidas) VALUES ('Michel Platini', 17, 5, 14);
INSERT IGNORE INTO Jogador (nome, idPais, totalGols, totalPartidas) VALUES ('Zico', 4, 5, 14);
INSERT IGNORE INTO Jogador (nome, idPais, totalGols, totalPartidas) VALUES ('Lukas Podolski', 1, 5, 15);
INSERT IGNORE INTO Jogador (nome, idPais, totalGols, totalPartidas) VALUES ('Olivier Giroud', 17, 5, 17);
INSERT IGNORE INTO Jogador (nome, idPais, totalGols, totalPartidas) VALUES ('Edinson Cavani', 36, 5, 17);
INSERT IGNORE INTO Jogador (nome, idPais, totalGols, totalPartidas) VALUES ('Franz Beckenbauer', 1, 5, 18);

-- Inserção de Participações de Jogadores
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (17, 1);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (18, 1);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (19, 1);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (20, 1);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (15, 2);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (16, 2);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (17, 2);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (18, 2);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (9, 3);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (10, 3);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (6, 4);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (18, 5);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (19, 5);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (20, 5);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (21, 5);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (22, 5);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (6, 6);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (7, 6);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (8, 6);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (9, 6);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (21, 7);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (22, 7);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (5, 8);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (14, 9);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (15, 9);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (16, 9);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (5, 10);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (6, 10);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (13, 11);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (14, 11);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (15, 12);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (16, 12);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (17, 12);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (9, 13);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (11, 13);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (12, 13);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (19, 14);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (20, 14);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (21, 14);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (22, 14);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (10, 15);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (11, 15);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (12, 15);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (4, 16);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (8, 17);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (16, 18);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (17, 18);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (6, 19);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (7, 19);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (18, 20);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (19, 20);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (20, 20);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (11, 21);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (12, 21);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (13, 21);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (8, 22);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (9, 22);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (10, 22);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (14, 23);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (15, 23);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (16, 23);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (11, 24);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (12, 24);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (13, 24);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (6, 25);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (7, 25);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (8, 25);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (9, 25);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (1, 26);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (2, 27);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (3, 27);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (4, 28);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (5, 28);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (21, 29);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (22, 29);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (20, 30);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (21, 30);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (22, 30);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (16, 31);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (17, 31);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (13, 32);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (14, 32);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (15, 32);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (12, 33);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (13, 33);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (14, 33);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (15, 33);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (18, 34);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (19, 34);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (20, 34);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (21, 34);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (22, 34);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (2, 35);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (3, 35);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (6, 36);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (7, 36);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (8, 36);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (13, 37);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (14, 37);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (10, 38);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (11, 38);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (12, 38);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (10, 39);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (11, 39);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (19, 40);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (20, 40);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (21, 40);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (22, 40);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (5, 41);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (6, 41);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (7, 41);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (5, 42);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (15, 43);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (5, 44);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (5, 45);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (2, 46);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (3, 46);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (20, 47);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (22, 47);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (14, 48);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (14, 49);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (16, 49);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (17, 49);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (20, 50);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (21, 50);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (7, 51);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (8, 51);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (9, 51);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (15, 52);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (16, 52);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (17, 53);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (19, 53);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (20, 53);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (18, 54);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (19, 54);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (20, 54);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (15, 55);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (16, 55);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (10, 56);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (11, 56);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (9, 57);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (10, 57);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (11, 57);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (14, 58);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (15, 58);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (16, 58);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (18, 59);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (19, 59);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (20, 59);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (11, 60);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (12, 60);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (13, 60);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (20, 61);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (21, 61);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (22, 61);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (16, 62);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (17, 62);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (18, 62);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (19, 62);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (18, 63);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (19, 63);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (20, 63);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (18, 64);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (19, 64);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (20, 64);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (10, 65);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (11, 65);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (12, 65);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (12, 66);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (13, 66);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (14, 66);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (15, 66);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (16, 66);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (1, 67);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (3, 68);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (3, 69);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (6, 70);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (14, 71);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (4, 72);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (5, 72);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (8, 73);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (9, 73);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (17, 74);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (19, 74);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (12, 75);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (13, 75);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (15, 76);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (16, 77);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (17, 77);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (14, 78);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (15, 78);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (20, 79);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (21, 79);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (14, 80);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (15, 80);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (16, 80);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (17, 80);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (18, 81);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (19, 81);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (20, 81);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (21, 81);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (6, 82);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (7, 82);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (12, 83);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (14, 83);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (15, 83);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (13, 84);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (14, 84);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (11, 85);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (12, 85);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (16, 86);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (17, 86);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (18, 86);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (19, 87);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (20, 87);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (21, 87);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (22, 87);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (20, 88);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (21, 88);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (22, 88);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (6, 89);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (7, 89);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (8, 89);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (10, 90);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (11, 90);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (14, 91);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (15, 91);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (16, 91);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (17, 91);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (16, 92);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (17, 92);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (18, 92);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (17, 93);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (18, 93);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (19, 93);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (19, 94);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (20, 94);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (21, 94);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (15, 95);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (17, 95);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (18, 95);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (11, 96);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (12, 96);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (13, 96);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (11, 97);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (12, 97);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (13, 97);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (18, 98);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (19, 98);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (20, 98);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (20, 99);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (21, 99);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (22, 99);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (19, 100);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (20, 100);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (21, 100);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (22, 100);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (8, 101);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (9, 101);
INSERT IGNORE INTO ParticipacaoJogador (idEdicao, idJogador) VALUES (10, 101);
